
-- Create a table with indexes that have large number of partially empty 
-- blocks and will benefit from an index coalesce

-- Create a table, indexes and gather statistics

DROP SEQUENCE ctest_pk_seq;

DROP TABLE CTEST PURGE;

CREATE TABLE CTEST AS SELECT * FROM CUSTOMERS where 1=2;

CREATE INDEX CTEST_LASTNAME ON CTEST (CUST_LAST_NAME);

CREATE INDEX CTEST_COUNTRY ON CTEST ( COUNTRY_ID);

-- Modify the table to create skewed data on Country_id

CREATE SEQUENCE ctest_pk_seq START WITH 200000 NOMAXVALUE;

INSERT INTO CTEST SELECT * FROM CUSTOMERS;

INSERT INTO CTEST
SELECT ctest_pk_seq.nextval, CUST_FIRST_NAME, CUST_LAST_NAME, CUST_GENDER,
	CUST_YEAR_OF_BIRTH,CUST_MARITAL_STATUS,CUST_STREET_ADDRESS,
	CUST_POSTAL_CODE,CUST_CITY,CUST_CITY_ID,CUST_STATE_PROVINCE,
	 CUST_STATE_PROVINCE_ID, COUNTRY_ID, CUST_MAIN_PHONE_NUMBER,
	 CUST_INCOME_LEVEL, CUST_CREDIT_LIMIT,
	CUST_EMAIL, CUST_TOTAL,CUST_TOTAL_ID,CUST_SRC_ID,CUST_EFF_FROM,
	CUST_EFF_TO,CUST_VALID 
FROM CUSTOMERS;

INSERT INTO CTEST
SELECT ctest_pk_seq.nextval, CUST_FIRST_NAME, CUST_LAST_NAME, CUST_GENDER,
        CUST_YEAR_OF_BIRTH,CUST_MARITAL_STATUS,CUST_STREET_ADDRESS,
        CUST_POSTAL_CODE,CUST_CITY,CUST_CITY_ID,CUST_STATE_PROVINCE,
         CUST_STATE_PROVINCE_ID, COUNTRY_ID, CUST_MAIN_PHONE_NUMBER,
         CUST_INCOME_LEVEL, CUST_CREDIT_LIMIT,
        CUST_EMAIL, CUST_TOTAL,CUST_TOTAL_ID,CUST_SRC_ID,CUST_EFF_FROM,
        CUST_EFF_TO,CUST_VALID
FROM CUSTOMERS

INSERT INTO CTEST
SELECT ctest_pk_seq.nextval, CUST_FIRST_NAME, CUST_LAST_NAME, CUST_GENDER,
        CUST_YEAR_OF_BIRTH,CUST_MARITAL_STATUS,CUST_STREET_ADDRESS,
        CUST_POSTAL_CODE,CUST_CITY,CUST_CITY_ID,CUST_STATE_PROVINCE,
         CUST_STATE_PROVINCE_ID, COUNTRY_ID, CUST_MAIN_PHONE_NUMBER,
         CUST_INCOME_LEVEL, CUST_CREDIT_LIMIT,
        CUST_EMAIL, CUST_TOTAL,CUST_TOTAL_ID,CUST_SRC_ID,CUST_EFF_FROM,
        CUST_EFF_TO,CUST_VALID
FROM CUSTOMERS;

DELETE FROM CTEST 
WHERE mod(cust_id,2) = 1;

commit;

EXEC DBMS_STATS.GATHER_TABLE_STATS('SH','CTEST');

-- SQL statement that will use full table scan instead of index lookup 
-- until index is coalesced

SET AUTOTRACE TRACEONLY
select cust_id, cust_last_name, cust_total
 from ctest
where cust_last_name between '&1' and '&2'
/
