SET ECHO ON

CONNECT / as sysdba

DROP TABLESPACE TESTLM INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE TESTLM 
DATAFILE '/u01/app/oracle/oradata/orcl/testlm1.dbf' 
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 300M
SEGMENT SPACE MANAGEMENT MANUAL;

CONNECT sh/sh

-- Create a table with indexes that have large number of 
-- partially empty blocks and will benefit from an index 
-- coalesce

-- Create a table, indexes and gather statistics
DROP SEQUENCE ctest_pk_seq;

DROP TABLE CTEST PURGE;

CREATE TABLE CTEST TABLESPACE TESTLM
AS SELECT *
 FROM CUSTOMERS where 1=2;

ALTER TABLE CTEST ADD Constraint CTEST_PK 
	Primary KEY (cust_id);
ALTER TABLE CTEST ADD (DUMMY VARCHAR2(300));


CREATE SEQUENCE ctest_pk_seq START WITH 200000 NOMAXVALUE;

INSERT INTO CTEST
SELECT ctest_pk_seq.nextval, CUST_FIRST_NAME,
   CUST_LAST_NAME,CUST_GENDER, CUST_YEAR_OF_BIRTH,
   CUST_MARITAL_STATUS,CUST_STREET_ADDRESS,CUST_POSTAL_CODE,
   CUST_CITY,CUST_CITY_ID,CUST_STATE_PROVINCE,
   CUST_STATE_PROVINCE_ID,COUNTRY_ID,CUST_MAIN_PHONE_NUMBER,
   CUST_INCOME_LEVEL,CUST_CREDIT_LIMIT,CUST_EMAIL,
   CUST_TOTAL,CUST_TOTAL_ID,CUST_SRC_ID,CUST_EFF_FROM,
   CUST_EFF_TO,CUST_VALID,
   CUST_FIRST_NAME||' '||CUST_LAST_NAME
FROM CUSTOMERS;


INSERT INTO CTEST
SELECT ctest_pk_seq.nextval, CUST_FIRST_NAME,
   CUST_LAST_NAME,CUST_GENDER, CUST_YEAR_OF_BIRTH,
   CUST_MARITAL_STATUS,CUST_STREET_ADDRESS,CUST_POSTAL_CODE,
   CUST_CITY,CUST_CITY_ID,CUST_STATE_PROVINCE,
   CUST_STATE_PROVINCE_ID,COUNTRY_ID,CUST_MAIN_PHONE_NUMBER,
   CUST_INCOME_LEVEL,CUST_CREDIT_LIMIT,CUST_EMAIL,
   CUST_TOTAL,CUST_TOTAL_ID,CUST_SRC_ID,CUST_EFF_FROM,
   CUST_EFF_TO,CUST_VALID,
   CUST_FIRST_NAME||' '||CUST_LAST_NAME
FROM CUSTOMERS;


INSERT INTO CTEST
SELECT ctest_pk_seq.nextval, CUST_FIRST_NAME,
   CUST_LAST_NAME,CUST_GENDER, CUST_YEAR_OF_BIRTH,
   CUST_MARITAL_STATUS,CUST_STREET_ADDRESS,CUST_POSTAL_CODE,
   CUST_CITY,CUST_CITY_ID,CUST_STATE_PROVINCE,
   CUST_STATE_PROVINCE_ID,COUNTRY_ID,CUST_MAIN_PHONE_NUMBER,
   CUST_INCOME_LEVEL,CUST_CREDIT_LIMIT,CUST_EMAIL,
   CUST_TOTAL,CUST_TOTAL_ID,CUST_SRC_ID,CUST_EFF_FROM,
   CUST_EFF_TO,CUST_VALID,
   CUST_FIRST_NAME||' '||CUST_LAST_NAME
FROM CUSTOMERS;


INSERT INTO CTEST
SELECT ctest_pk_seq.nextval, CUST_FIRST_NAME,
   CUST_LAST_NAME,CUST_GENDER, CUST_YEAR_OF_BIRTH,
   CUST_MARITAL_STATUS,CUST_STREET_ADDRESS,CUST_POSTAL_CODE,
   CUST_CITY,CUST_CITY_ID,CUST_STATE_PROVINCE,
   CUST_STATE_PROVINCE_ID,COUNTRY_ID,CUST_MAIN_PHONE_NUMBER,
   CUST_INCOME_LEVEL,CUST_CREDIT_LIMIT,CUST_EMAIL,
   CUST_TOTAL,CUST_TOTAL_ID,CUST_SRC_ID,CUST_EFF_FROM,
   CUST_EFF_TO,CUST_VALID,
   CUST_FIRST_NAME||' '||CUST_LAST_NAME
FROM CUSTOMERS;

DELETE FROM CTEST 
WHERE mod(cust_id,2) = 1;

commit;

EXEC DBMS_STATS.GATHER_TABLE_STATS('SH','CTEST',-
   method_opt=>'FOR ALL INDEXED COLUMNS SIZE AUTO');

