-- Create a table with indexes that will yield a different
-- execution plan when statistics are gathered

-- Create a table, indexes and gather statistics

DROP SEQUENCE ctest_pk_seq;

DROP TABLE CTEST PURGE;

CREATE TABLE CTEST AS SELECT * FROM CUSTOMERS;

ALTER TABLE CTEST MODIFY (CUST_ID PRIMARY KEY);

CREATE INDEX CTEST_LASTNAME ON CTEST (CUST_LAST_NAME);

CREATE INDEX CTEST_COUNTRY ON CTEST ( COUNTRY_ID);

EXECUTE DBMS_STATS.GATHER_TABLE_STATS('SH','CTEST');

-- Modify the table to create skewed data on Country_id

CREATE SEQUENCE ctest_pk_seq START WITH 200000 NOMAXVALUE;

INSERT INTO CTEST
SELECT ctest_pk_seq.nextval,CUST_FIRST_NAME,
    CUST_LAST_NAME, CUST_GENDER,CUST_YEAR_OF_BIRTH,
    CUST_MARITAL_STATUS, CUST_STREET_ADDRESS,
    CUST_POSTAL_CODE,CUST_CITY, CUST_CITY_ID,
    CUST_STATE_PROVINCE,CUST_STATE_PROVINCE_ID,COUNTRY_ID,
    CUST_MAIN_PHONE_NUMBER, CUST_INCOME_LEVEL,
    CUST_CREDIT_LIMIT,CUST_EMAIL,CUST_TOTAL,CUST_TOTAL_ID,
    CUST_SRC_ID,CUST_EFF_FROM, CUST_EFF_TO,CUST_VALID 
FROM CTEST
WHERE country_id = 52790;

INSERT INTO CTEST
SELECT ctest_pk_seq.nextval, CUST_FIRST_NAME,
    CUST_LAST_NAME, CUST_GENDER,CUST_YEAR_OF_BIRTH,
    CUST_MARITAL_STATUS, CUST_STREET_ADDRESS,
    CUST_POSTAL_CODE,CUST_CITY, CUST_CITY_ID,
    CUST_STATE_PROVINCE,CUST_STATE_PROVINCE_ID,COUNTRY_ID,
    CUST_MAIN_PHONE_NUMBER,CUST_INCOME_LEVEL,
    CUST_CREDIT_LIMIT,CUST_EMAIL,CUST_TOTAL,CUST_TOTAL_ID,
    CUST_SRC_ID,CUST_EFF_FROM, CUST_EFF_TO,CUST_VALID
FROM CTEST
WHERE country_id = 52790;

