CREATE OR REPLACE TRIGGER manage_service after startup on database
DECLARE
	role VARCHAR(30);
BEGIN
	SELECT DATABASE_ROLE INTO role FROM V$DATABASE;
	IF role = 'PRIMARY' THEN
		DBMS_SERVICE. START_SERVICE ('PC01PROD');
	ELSE
		DBMS_SERVICE. STOP_SERVICE ('PC01PROD');
	END IF;
END;
/
