-- setup_bulk load workload
-- create 20 users 
-- assign each to a new tablespace

ALTER SESSION SET DB_CREATE_FILE_DEST = '&1';

CREATE TABLESPACE LOADTEST1 
DATAFILE SIZE 5M AUTOEXTEND ON NEXT 5M MAXSIZE 100M 
/
CREATE TABLESPACE LOADTEST2 
DATAFILE SIZE 5M AUTOEXTEND ON NEXT 5M MAXSIZE 100M 
/
CREATE TABLESPACE LOADTEST3 
DATAFILE SIZE 5M AUTOEXTEND ON NEXT 5M MAXSIZE 100M 
/
CREATE TABLESPACE LOADTEST4 
DATAFILE SIZE 5M AUTOEXTEND ON NEXT 5M MAXSIZE 100M 
/
CREATE TABLESPACE LOADTEST5 
DATAFILE SIZE 5M AUTOEXTEND ON NEXT 5M MAXSIZE 100M 
/
CREATE TABLESPACE LOADTEST6 
DATAFILE SIZE 5M AUTOEXTEND ON NEXT 5M MAXSIZE 100M 
/
CREATE TABLESPACE LOADTEST7 
DATAFILE SIZE 5M AUTOEXTEND ON NEXT 5M MAXSIZE 100M 
/
CREATE TABLESPACE LOADTEST8 
DATAFILE SIZE 5M AUTOEXTEND ON NEXT 5M MAXSIZE 100M 
/
CREATE TABLESPACE LOADTEST9 
DATAFILE SIZE 5M AUTOEXTEND ON NEXT 5M MAXSIZE 100M 
/
CREATE TABLESPACE LOADTEST10 
DATAFILE SIZE 5M AUTOEXTEND ON NEXT 5M MAXSIZE 100M 
/

CREATE user USER1 IDENTIFIED BY USER1 
DEFAULT TABLESPACE LOADTEST1
QUOTA UNLIMITED on LOADTEST1;

GRANT CREATE SESSION, CREATE TABLE TO USER1;

CREATE user USER2 IDENTIFIED BY USER2 
DEFAULT TABLESPACE LOADTEST2
QUOTA UNLIMITED on LOADTEST2;

GRANT CREATE SESSION, CREATE TABLE TO USER2;

CREATE user USER3 IDENTIFIED BY USER3 
DEFAULT TABLESPACE LOADTEST3
QUOTA UNLIMITED on LOADTEST3;

GRANT CREATE SESSION, CREATE TABLE TO USER3;

CREATE user USER4 IDENTIFIED BY USER4 
DEFAULT TABLESPACE LOADTEST4
QUOTA UNLIMITED on LOADTEST4;

GRANT CREATE SESSION, CREATE TABLE TO USER4;

CREATE user USER5 IDENTIFIED BY USER5 
DEFAULT TABLESPACE LOADTEST5
QUOTA UNLIMITED on LOADTEST5;

GRANT CREATE SESSION, CREATE TABLE TO USER5;

CREATE user USER6 IDENTIFIED BY USER6 
DEFAULT TABLESPACE LOADTEST6
QUOTA UNLIMITED on LOADTEST6;

GRANT CREATE SESSION, CREATE TABLE TO USER6;

CREATE user USER7 IDENTIFIED BY USER7 
DEFAULT TABLESPACE LOADTEST7
QUOTA UNLIMITED on LOADTEST7;

GRANT CREATE SESSION, CREATE TABLE TO USER7;

CREATE user USER8 IDENTIFIED BY USER8 
DEFAULT TABLESPACE LOADTEST8
QUOTA UNLIMITED on LOADTEST8;

GRANT CREATE SESSION, CREATE TABLE TO USER8;

CREATE user USER9 IDENTIFIED BY USER9 
DEFAULT TABLESPACE LOADTEST9
QUOTA UNLIMITED on LOADTEST9;

GRANT CREATE SESSION, CREATE TABLE TO USER9;

CREATE user USER10 IDENTIFIED BY USER10 
DEFAULT TABLESPACE LOADTEST10
QUOTA UNLIMITED on LOADTEST10;

GRANT CREATE SESSION, CREATE TABLE TO USER10;

CREATE user USER11 IDENTIFIED BY USER11 
DEFAULT TABLESPACE LOADTEST1
QUOTA UNLIMITED on LOADTEST1;

GRANT CREATE SESSION, CREATE TABLE TO USER11;

CREATE user USER12 IDENTIFIED BY USER12 
DEFAULT TABLESPACE LOADTEST2
QUOTA UNLIMITED on LOADTEST2;

GRANT CREATE SESSION, CREATE TABLE TO USER12;

CREATE user USER13 IDENTIFIED BY USER13 
DEFAULT TABLESPACE LOADTEST3
QUOTA UNLIMITED on LOADTEST3;

GRANT CREATE SESSION, CREATE TABLE TO USER13;

CREATE user USER14 IDENTIFIED BY USER14 
DEFAULT TABLESPACE LOADTEST4
QUOTA UNLIMITED on LOADTEST4;

GRANT CREATE SESSION, CREATE TABLE TO USER14;

CREATE user USER15 IDENTIFIED BY USER15 
DEFAULT TABLESPACE LOADTEST5
QUOTA UNLIMITED on LOADTEST5;

GRANT CREATE SESSION, CREATE TABLE TO USER15;

CREATE user USER16 IDENTIFIED BY USER16 
DEFAULT TABLESPACE LOADTEST6
QUOTA UNLIMITED on LOADTEST6;

GRANT CREATE SESSION, CREATE TABLE TO USER16;

CREATE user USER17 IDENTIFIED BY USER17 
DEFAULT TABLESPACE LOADTEST7
QUOTA UNLIMITED on LOADTEST7;

GRANT CREATE SESSION, CREATE TABLE TO USER17;

CREATE user USER18 IDENTIFIED BY USER18 
DEFAULT TABLESPACE LOADTEST8
QUOTA UNLIMITED on LOADTEST8;

GRANT CREATE SESSION, CREATE TABLE TO USER18;

CREATE user USER19 IDENTIFIED BY USER19 
DEFAULT TABLESPACE LOADTEST9
QUOTA UNLIMITED on LOADTEST9;

GRANT CREATE SESSION, CREATE TABLE TO USER19;

CREATE user USER20 IDENTIFIED BY USER20 
DEFAULT TABLESPACE LOADTEST10
QUOTA UNLIMITED on LOADTEST10;

GRANT CREATE SESSION, CREATE TABLE TO USER20;

