
ALTER TABLE CUSTOMERS CACHE;
ALTER TABLE WAREHOUSES CACHE;
ALTER TABLE ORDER_ITEMS CACHE;
ALTER TABLE ORDERS CACHE;
ALTER TABLE INVENTORIES CACHE;
ALTER TABLE PRODUCT_INFORMATION CACHE;
ALTER TABLE PRODUCT_DESCRIPTIONS CACHE;
ALTER TABLE PROMOTIONS CACHE;
