ALTER TABLE CUSTOMERS NOCACHE;
ALTER TABLE WAREHOUSES NOCACHE;
ALTER TABLE ORDER_ITEMS NOCACHE;
ALTER TABLE ORDERS NOCACHE;
ALTER TABLE INVENTORIES NOCACHE;
ALTER TABLE PRODUCT_INFORMATION NOCACHE;
ALTER TABLE PRODUCT_DESCRIPTIONS NOCACHE;
ALTER TABLE PROMOTIONS NOCACHE;
