
ALTER TABLE sales cache;

ALTER TABLE COSTS CACHE;

ALTER TABLE TIMES CACHE;
ALTER TABLE PRODUCTS CACHE;
ALTER TABLE CHANNELS CACHE;
ALTER TABLE PROMOTIONS CACHE;
ALTER TABLE CUSTOMERS CACHE;
ALTER TABLE COUNTRIES CACHE;
ALTER TABLE CAL_MONTH_SALES_MV CACHE;
