
ALTER TABLE sales nocache;

ALTER TABLE COSTS NOCACHE;

ALTER TABLE TIMES NOCACHE;
ALTER TABLE PRODUCTS NOCACHE;
ALTER TABLE CHANNELS NOCACHE;
ALTER TABLE PROMOTIONS NOCACHE;
ALTER TABLE CUSTOMERS NOCACHE;
ALTER TABLE COUNTRIES NOCACHE;
ALTER TABLE CAL_MONTH_SALES_MV NOCACHE;
ALTER TABLE SALES NOCACHE;
