#!/bin/bash
# Script to select the appropriate workload scripts
#

practice=$1
section=$2
value=$1$2

case $value in 

2[1-3])
# take AWR and statspack snapshots
    ./snapshots.sh
# Small OLPT workload to generate buffer busy waits and demo AWR
    ./order_app_load.sh 8
;;

31) 
# start a workload to produce a ???
    ./start_31.sh
;;

4[1-2]) 
# 4-1 is med OLPT workload with IO load to diagnose OS issues
# 4-2 is medium OLTP workload w/o IO
   ./wksh_w$value.sh
;;	
51) 
# start a workload to produce a load
    ./wksh_w$value.sh
;;
61) 
# start a workload to produce a 12 txnaction per second load
    ./baseline_wkld.sh &
;;
81) 
# start a workload to produce a unequal load on 3 services
    ./start_sys_81.sh &
    ./start_jfv_81.sh &
    ./wksh_w81_orcl.sh &
;;
71) 
# start a workload to produce a load
    ./wksh_w$value.sh
;;
REPLAY) 
# hard parse workload was 8-1
   ./hard_parse_wkld.sh 
;;
HARDPARSE) 
# hard parse workload was 8-1
   ./hard_parse_wkld.sh 
;;
SP)
#  soft parse workload
    ./wksh_SP.sh  3
;;
KEEP)
# Demo Keep Objects in Shared pool
# changed load script from 10g
    ./order_app_load.sh 2 
;;
BC)
# Buffer cache problems
# Use bufffer cache advisor to fix undersized cache
# Use same workload to use Keep pool
# use same load for ASMM tuning
	./snapshots.sh
	./wksh_BC.sh 2
;;
ASMM)
	./snapshots.sh
	./wksh_BC.sh 2
;;
AMM) 
# Using AMM to adjust for changing workload
# the BC workload increases 
# and a new workload AMM is added
# observer the ASMM changes to the memory allocation
    ./snapshots.sh
    ./wksh_BC.sh 2
    ./wksh_PGA.sh 1
;;
111) 
# Create a workload that leads to REDO and checkpoint issues
    ./wksh_w111.sh 5
;;
PGA) 
# Simulate a DSS workload that uses significant Sort areas
	./snapshots.sh
	./wksh_PGA.sh 2
;;
141) 
# Compare the differences in a workload that causes freelist
# contention between dictionary managed, locally managed

    ./wksh_w$value.sh 12 2000 8
;;

*) 
echo "Usage: ./workgen [lesson practice]|{scenario]"
echo "Example: ./workgen 3 1"
echo "Example: ./workgen SP"
esac
